#! /bin/bash
set -e

requires \
    opam \
    why3
main() {
    #
    # Install Frama-C
    #
    export OPAMYES=1
    opam install frama-c --no-depext --update-invariant
    eval "$(opam env)"
    opam upgrade
    why3 config detect
}
main "$@"
