#! /bin/bash
set -e

requires \
    clang \
    git \
    cmake \
    make \
    z3
main() {
    #
    # Install KLEE
    #
    local SRC_DIRECTORY="${HOME}/klee"
    local BUILD_DIRECTORY="${SRC_DIRECTORY}/build"
    git clone https://github.com/klee/klee.git "${SRC_DIRECTORY}"
    mkdir -p "${BUILD_DIRECTORY}"
    pushd "${BUILD_DIRECTORY}" > /dev/null || exit
    cmake -DENABLE_SOLVER_Z3=ON -DENABLE_POSIX_RUNTIME=ON -DENABLE_UNIT_TESTS=OFF -DENABLE_SYSTEM_TESTS=OFF "${SRC_DIRECTORY}"
    make
    mkdir -p "${HOME}/.local/bin"
    ln -s "${BUILD_DIRECTORY}/bin/klee" "${HOME}/.local/bin/klee"
    popd > /dev/null || exit
}
main "$@"
