#! /bin/bash
set -e

requires \
    code-server \
    download_extensions \
    curl \
    jq
try_download() {
    local EXTENSION="${ARG}.vsix"
    echo "Failed to install ${ARG}, attempting to download and install from local copy..."
    download_extensions "${ARG}"
    install_extensions "${EXTENSION}"
    rm "${EXTENSION}"
}
main() {
    #
    # Download Extensions listing
    #
    CONFIG="${CODE_SERVER_CONFIG_DIR:-/app/code-server/config}/config.yaml"
    EXTENSIONS_JSON="${CODE_SERVER_CONFIG_DIR:-/app/code-server/config}/Extensions.json"
    curl -o "${EXTENSIONS_JSON}" https://raw.githubusercontent.com/jhwohlgemuth/purple/main/artifacts/Extensions.json
    #
    # Install Code Server extensions
    #
    if [[ -z "$1" ]]; then
        ARGS=development
    else
        ARGS=("$@")
    fi
    for ARG in "${ARGS[@]}"; do
        if echo "${ARG}" | grep -iq "[.]"; then
            trap try_download ERR
            echo "Identified ${ARG}..."
            code-server --config "${CONFIG}" --install-extension "${ARG}" --force
        else
            EXTENSIONS="$(jq -r ".${ARG}[]" "${EXTENSIONS_JSON}")"
            for EXTENSION in ${EXTENSIONS}; do
                install_extensions "${EXTENSION}" || true
            done
        fi
    done
}
main "$@"
