#! /bin/bash
set -e

requires \
    cargo \
    git \
    opam
install_coq_of_rust() {
    git clone https://github.com/formal-land/coq-of-rust "${HOME}/coq-of-rust"
    pushd "${HOME}/coq-of-rust" > /dev/null || return
    cargo install --path lib/
    popd > /dev/null || return
    rm -frd "${HOME}/coq-of-rust"
}
main() {
    export OPAMYES=1
    #
    # Install opam dependencies
    #
    opam install \
        core_unix \
        domainslib \
        easy_logging \
        ocamlgraph \
        odoc \
        ppx_deriving \
        progress \
        unionFind \
        visitors \
        yojson \
        zarith
    eval "$(opam env)"
    #
    # Install Charon and Aeneas
    #
    mkdir -p "${HOME}/aeneas-toolchain"
    git clone https://github.com/AeneasVerif/aeneas "${HOME}/aeneas-toolchain/aeneas"
    git clone https://github.com/AeneasVerif/charon "${HOME}/aeneas-toolchain/charon"
    pushd "${HOME}/aeneas-toolchain" > /dev/null || exit
    pushd "${HOME}/aeneas-toolchain/charon" > /dev/null || exit
    make build-charon-rust build-charon-ml
    mv bin/* "${HOME}/.local/bin"
    popd > /dev/null || exit
    if is_command charon; then
        pushd "${HOME}/aeneas-toolchain/aeneas" > /dev/null || exit
        make setup-charon && make
        chmod +x ./bin/aeneas
        mv ./bin/aeneas "${HOME}/.local/bin"
        install_coq_of_rust
        popd > /dev/null || exit
    else
        echo "=> [ERROR] Invalid charon link"
    fi
    popd > /dev/null || exit
    rm -frd "${HOME}/aeneas-toolchain"
}
main "$@"
