#! /bin/bash
set -e

requires curl
main() {
    #
    # Install bflat
    #
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local HOME="${1:-/home/nonroot}"
    local VERSION="${2:-"8.0.0"}"
    local SRC_DIRECTORY="${HOME}/bflat"
    mkdir -p "${SRC_DIRECTORY}"
    cd "${SRC_DIRECTORY}" || exit
    curl -o bflat.tar.gz -LJ "https://github.com/bflattened/bflat/releases/download/v${VERSION}/bflat-${VERSION}-linux-glibc-x64.tar.gz"
    tar -xvf bflat.tar.gz
    chmod +x bflat
    mv bflat /usr/local/bin
    cd "${PWD}" || exit
    rm -frd "${SRC_DIRECTORY}/bflat"
}
main "$@"
