#! /bin/bash
set -e

requires \
    git \
    make \
    rustc
main() {
    local SRC_DIRECTORY="${HOME}/rust2ada"
    git clone https://github.com/IntuitionAmiga/rust2ada.git "${SRC_DIRECTORY}"
    pushd "${SRC_DIRECTORY}" > /dev/null || exit
    make
    mkdir -p "${HOME}/.local/bin"
    ln -sf "${SRC_DIRECTORY}/rust2ada" "${HOME}/.local/bin/"
    popd > /dev/null || exit
    requires rust2ada
}
main "$@"
