#! /bin/bash
set -e

requires \
    curl \
    libzmq5
main() {
    curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
    sh init.sh -y
    rm init.sh
    export PATH="${PATH}:${HOME}/.nimble/bin"
    choosenim stable
    nimble install jupyternim -y
    # shellcheck disable=SC2016
    echo 'export PATH="${PATH}:${HOME}/.nimble/bin"' >> "${HOME}/.zshrc"
    printf "\n=> [WARNING] Run 'source \${HOME}/.zshrc' or restart your shell to apply PATH changes\n"
}
main "$@"
