#! /bin/bash
set -e

requires \
    curl \
    git \
    make \
    opam \
    python \
    unzip
install_alt_ergo() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    export OPAMYES=1
    #
    # Install Alt-Ergo (free)
    #
    opam install alt-ergo-free
    eval "$(opam env)"
    cd "${PWD}" || exit
}
install_cvc5() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"

    cd "${PWD}" || exit
}
install_vampire() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install Vampire
    #
    mkdir -p "${HOME}/vampire"
    cd "${HOME}/vampire" || exit
    curl -o source.zip -LJ https://github.com/vprover/vampire/releases/download/snakeForV4.7%2B/vampire-snake-static4starexec.zip
    unzip source.zip
    mv bin/* "${INSTALL_DIRECTORY}"
    cd "${PWD}" || exit
    rm -frd "${HOME}/vampire"
}
install_why3() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install Why3 and add provers
    #
    export OPAMYES=1
    opam install why3
    eval "$(opam env)"
    why3 config detect
    cd "${PWD}" || exit
}
install_z3() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install Z3
    #
    git clone https://github.com/Z3Prover/z3.git "${HOME}/z3"
    cd "${HOME}/z3" || exit
    python scripts/mk_make.py
    cd build || exit
    make -j8 && make install
    cd "${PWD}" || exit
    rm -frd "${HOME}/z3"
}
main() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local INSTALL_DIRECTORY="${HOME}/.local/bin"
    mkdir -p "${INSTALL_DIRECTORY}"
    #
    # Install CVC5
    #
    install_cvc5 "${INSTALL_DIRECTORY}"
    #
    # Install Vampire
    #
    mkdir -p "${HOME}/vampire"
    cd "${HOME}/vampire" || exit
    curl -o source.zip -LJ https://github.com/vprover/vampire/releases/download/snakeForV4.7%2B/vampire-snake-static4starexec.zip
    unzip source.zip
    mv bin/* "${INSTALL_DIRECTORY}"
    cd "${PWD}" || exit
    rm -frd "${HOME}/vampire"
    #
    # Install eprover
    #
    git clone https://github.com/eprover/eprover.git "${HOME}/eprover"
    cd "${HOME}/eprover" || exit
    ./configure && make -j8 && make install
    mv PROVER/* "${INSTALL_DIRECTORY}"
    cd "${PWD}" || exit
    rm -frd "${HOME}/eprover"
    #
    # Install Z3
    #
    git clone https://github.com/Z3Prover/z3.git "${HOME}/z3"
    cd "${HOME}/z3" || exit
    python scripts/mk_make.py
    cd build || exit
    make -j8 && make install
    cd "${PWD}" || exit
    rm -frd "${HOME}/z3"
    #
    # Install Alt-Ergo (free)
    #
    export OPAMYES=1
    opam install alt-ergo-free
    eval "$(opam env)"
    #
    # Install Why3 and add provers
    #
    export OPAMYES=1
    opam install why3
    eval "$(opam env)"
    why3 config detect
    cd "${PWD}" || exit
}
main "$@"
