#! /bin/bash
set -e

requires \
    git \
    install_extensions \
    jq
main() {
    install_java
    source "${HOME}/.zshrc"
    #
    # Install Prusti crate
    #
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    git clone git@github.com:viperproject/prusti-dev.git /prusti
    cd /prusti || exit
    ./x.py setup && ./x.py build --release
    # shellcheck disable=SC2016
    echo 'export PATH="/prusti/bin:${PATH}"' >> "${HOME}/.zshrc"
    export PATH="/prusti/bin:${PATH}"
    #
    # Install Prusti VSCode extension
    #
    install_extensions viper-admin.prusti-assistant
    #
    # Configure JAVA_HOME in Prusti extension settings
    #

}
main "$@"
