#! /bin/bash
set -e

requires \
    cargo \
    git \
    libcairo2-dev \
    libgtk-3-dev \
    libgtksourceview-3.0-dev \
    rsync \
    why3 \
    z3
main() {
    #
    # Install Creusot
    #
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local SRC_DIRECTORY="${HOME}/creusot"
    git clone https://github.com/creusot-rs/creusot "${SRC_DIRECTORY}"
    cd "${SRC_DIRECTORY}" || exit
    ./INSTALL
    cargo creusot --help
    cd "${PWD}" || exit
}
main "$@"
