#! /bin/bash
set -e

requires \
    cargo \
    git \
    wget
main() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local VERUS_INSTALLATION_DIRECTORY="${HOME}/verus"
    local VERUS_SOURCE="${VERUS_INSTALLATION_DIRECTORY}/source"
    git clone https://github.com/verus-lang/verus "${VERUS_INSTALLATION_DIRECTORY}"
    #
    # Install local z3
    #
    cd "${VERUS_SOURCE}/tools"
    bash ./get-z3.sh
    export VERUS_Z3_PATH="${VERUS_SOURCE}/tools/z3"
    #
    # Install Verus
    #
    cd "${VERUS_INSTALLATION_DIRECTORY}" || exit
    chmod +x "${VERUS_INSTALLATION_DIRECTORY}/tools/activate"
    "${VERUS_INSTALLATION_DIRECTORY}/tools/activate"
    "${VERUS_INSTALLATION_DIRECTORY}/tools/vargo/target/release/vargo" build --release
    mkdir -p "${HOME}/.local/bin"
    ln -sf "${VERUS_SOURCE}/target-verus/release/verus" "${HOME}/.local/bin/verus"
    #
    # Install verusfmt
    #
    cargo install verusfmt --locked
    cd "${PWD}" || exit
    #
    # Inform user about PATH
    #
    echo "Verus installed successfully!"
    echo "Make sure ${HOME}/.local/bin is in your PATH."
    echo "You can add it by adding this line to your shell rc file:"
    echo 'export PATH="${HOME}/.local/bin:${PATH}"'
}
main "$@"
