#! /bin/bash
set -e

requires \
    cargo \
    git \
    java \
    python3
main() {
    #
    # Install Prusti crate
    #
    local SRC_DIRECTORY="${HOME}/prusti"
    git clone https://github.com/viperproject/prusti-dev.git "${SRC_DIRECTORY}"
    pushd "${SRC_DIRECTORY}" > /dev/null || exit
    ./x.py setup && ./x.py build --release
    mkdir -p "${HOME}/.local/bin"
    mv "${SRC_DIRECTORY}/target/release/prusti-rustc" "${HOME}/.local/bin/"
    mv "${SRC_DIRECTORY}/target/release/cargo-prusti" "${HOME}/.local/bin/"
    chmod +x "${HOME}/.local/bin/prusti-rustc"
    chmod +x "${HOME}/.local/bin/cargo-prusti"
    # shellcheck disable=SC2016
    echo 'export PATH="${HOME}/prusti/bin:${PATH}"' >> "${HOME}/.zshrc"
    export PATH="${SRC_DIRECTORY}/bin:${PATH}"
    popd > /dev/null || exit
    rm -rf "${SRC_DIRECTORY}"
}
main "$@"
