#! /bin/bash
set -e

requires \
    conda \
    git
main() {
    #
    # Install LPython compiler
    #
    local CONDA_ENV='lp'
    local SRC_DIRECTORY="${HOME}/lpython"
    git clone https://github.com/lcompilers/lpython.git "${SRC_DIRECTORY}"
    pushd "${SRC_DIRECTORY}" > /dev/null || exit
    git submodule update --init
    conda env create -f environment_unix.yml
    conda run -n "${CONDA_ENV}" ./build0.sh
    conda run -n "${CONDA_ENV}" ./build1.sh
    mkdir -p "${HOME}/.local/bin"
    ln -sf "${SRC_DIRECTORY}/src/bin/lpython" "${HOME}/.local/bin/lpython"
    popd > /dev/null || exit
    conda env remove -n "${CONDA_ENV}"
    requires lpython
}
main "$@"
