#! /bin/bash
set -e

requires \
    curl
main() {
    local VERSION="${1:-"stable"}"
    curl -sSf https://elan.lean-lang.org/elan-init.sh | sh
    elan default "leanprover/lean4:${VERSION}"
}
main "$@"
