#! /bin/bash
set -e

requires \
    git \
    make
main() {
    #
    # Install Bison and Flex (Fast Lexical Analyzer Generator)
    #
    apt-get update
    apt-get install --no-install-recommends --yes bison flex
    #
    # Install Xr0 verifier
    #
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    git clone https://github.com/xr0-org/xr0 /xr0
    cd /xr0 || exit
    ./configure && make
    ln -s /xr0/bin/0v /usr/local/bin/0v
    echo 'export XR0_INCLUDES=/xr0/libx' >> "${HOME}/.zshrc"
    export XR0_INCLUDES=/xr0/libx
    cd "${PWD}" || exit
}
main "$@"
