#! /bin/bash
set -e

requires \
    curl \
    make
main() {
    local VERSION="${1:-"1.2.5"}"
    curl "https://musl.libc.org/releases/musl-${VERSION}.tar.gz" -o /tmp/musl.tar.gz
    tar -xvf /tmp/musl.tar.gz --directory /tmp
    pushd "/tmp/musl-${VERSION}" > /dev/null || exit
    mkdir -p "${HOME}/.local/bin"
    ./configure --exec-prefix="${HOME}/.local/bin"
    make && make install
    popd > /dev/null || exit
}
main "$@"
