#! /bin/bash
set -e

requires \
    curl
main() {
    local DEBIAN_VERSION
    DEBIAN_VERSION="$(lsb_release -rs)"
    curl -fsSL \
        "https://developer.download.nvidia.com/compute/cuda/repos/debian${DEBIAN_VERSION}/x86_64/cuda-keyring_1.1-1_all.deb" \
        -o cuda-keyring_1.1-1_all.deb
    sudo dpkg -i cuda-keyring_1.1-1_all.deb
    rm cuda-keyring_1.1-1_all.deb
    apt-get update
    apt-get install --yes cuda-toolkit
}
main "$@"
