#! /bin/bash
set -e

requires \
    curl \
    git \
    make \
    opam \
    python \
    unzip
install_alt_ergo() {
    export OPAMYES=1
    #
    # Install Alt-Ergo (free)
    #
    opam install alt-ergo-free
    eval "$(opam env)"
}
install_why3() {
    export OPAMYES=1
    #
    # Install Why3 and add provers
    #
    opam install why3
    eval "$(opam env)"
    why3 config detect
}
install_cvc5() {
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install CVC5
    #
    pushd "${INSTALL_DIRECTORY}" > /dev/null || exit
    curl -o cvc5 -LJ https://github.com/cvc5/cvc5/releases/download/cvc5-1.0.8/cvc5-Linux
    chmod +x cvc5
    popd > /dev/null || exit
}
install_vampire() {
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install Vampire
    #
    mkdir -p "${HOME}/vampire"
    pushd "${HOME}/vampire" > /dev/null || exit
    curl -o source.zip -LJ https://github.com/vprover/vampire/releases/download/snakeForV4.7%2B/vampire-snake-static4starexec.zip
    unzip source.zip
    mv bin/* "${INSTALL_DIRECTORY}"
    popd > /dev/null || exit
    rm -frd "${HOME}/vampire"
}
install_eprover() {
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install eprover
    #
    git clone https://github.com/eprover/eprover.git "${HOME}/eprover"
    pushd "${HOME}/eprover" > /dev/null || exit
    ./configure --prefix="${INSTALL_DIRECTORY}" && make -j8 && make install
    popd > /dev/null || exit
    rm -frd "${HOME}/eprover"
}
install_z3() {
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    #
    # Install Z3
    #
    git clone https://github.com/Z3Prover/z3.git "${HOME}/z3"
    pushd "${HOME}/z3" > /dev/null || exit
    python scripts/mk_make.py --prefix="${INSTALL_DIRECTORY}"
    pushd build > /dev/null || exit
    make -j8 && make install
    popd > /dev/null || exit
    popd > /dev/null || exit
    rm -frd "${HOME}/z3"
}
main() {
    local INSTALL_DIRECTORY="${1:-${HOME}/.local/bin}"
    mkdir -p "${INSTALL_DIRECTORY}"
    #
    # Install CVC5
    #
    install_cvc5 "${INSTALL_DIRECTORY}"
    #
    # Install Vampire
    #
    install_vampire "${INSTALL_DIRECTORY}"
    #
    # Install eprover
    #
    install_eprover "${INSTALL_DIRECTORY}"
    #
    # Install Z3
    #
    install_z3 "${INSTALL_DIRECTORY}"
    #
    # Install Alt-Ergo (free)
    #
    install_alt_ergo "${INSTALL_DIRECTORY}"
    #
    # Install Why3 and add provers
    #
    install_why3 "${INSTALL_DIRECTORY}"
}
main "$@"
