#! /bin/bash
set -e

requires \
    bison \
    flex \
    git \
    make
main() {
    #
    # Install Xr0 verifier
    #
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local XR0_ROOT="${HOME}/xr0"
    git clone https://github.com/xr0-org/xr0 "${XR0_ROOT}"
    cd "${XR0_ROOT}" || exit
    ./configure && make
    mkdir -p "${HOME}/.local/bin"
    ln -s "${XR0_ROOT}/bin/0v" "${HOME}/.local/bin/0v"
    # shellcheck disable=SC2016
    echo 'export XR0_INCLUDES="${HOME}/xr0/libx"' >> "${HOME}/.zshrc"
    export XR0_INCLUDES="${HOME}/libx"
    cd "${PWD}" || exit
    #
    # Inform user about PATH
    #
    echo "xr0 installed successfully!"
    echo "Make sure ${HOME}/.local/bin is in your PATH."
    echo "You can add it by adding this line to your shell rc file:"
    # shellcheck disable=SC2016
    echo 'export PATH="${HOME}/.local/bin:${PATH}"'
}
main "$@"
