#! /bin/bash
set -e

requires \
    curl \
    unzip
main() {
    local VERSION="${1:-"4.0.2"}"
    #
    # Install Cosmopolitan
    #
    curl "https://cosmo.zip/pub/cosmocc/cosmocc-${VERSION}.zip" --output /tmp/cosmocc.zip
    unzip /tmp/cosmocc.zip -d "${HOME}/cosmopolitan"
    # shellcheck disable=SC2016
    echo 'export PATH="${PATH}:${HOME}/cosmopolitan/bin"' >> "${HOME}/.zshrc"
    export PATH="${PATH}:${HOME}/cosmopolitan/bin"
    requires cosmocc
    printf "\n=> [WARNING] Run 'source \${HOME}/.zshrc' or restart your shell to apply PATH changes\n"
}
main "$@"
