#! /bin/bash
set -e

requires \
    binfmt-support \
    curl \
    unzip
install_ape_loader() {
    local APE_BIN_PATH="${HOME}/.local/bin/ape"
    #
    # Install APE loader
    #
    mkdir -p "${HOME}/.local/bin"
    curl -o "${APE_BIN_PATH}" "https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf"
    chmod +x "${APE_BIN_PATH}"
    mkdir -p /proc/sys/fs/binfmt_misc
    sudo mount -t binfmt_misc none /proc/sys/fs/binfmt_misc
    if [[ -f /proc/sys/fs/binfmt_misc/register ]]; then
        sudo sh -c "echo ':APE:M::MZqFpD::${APE_BIN_PATH}:' >/proc/sys/fs/binfmt_misc/register"
        sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
    fi
    update-binfmts --enable
}
main() {
    local VERSION="${1:-"4.0.2"}"
    #
    # Install Cosmopolitan
    #
    curl "https://cosmo.zip/pub/cosmocc/cosmocc-${VERSION}.zip" --output /tmp/cosmocc.zip
    unzip /tmp/cosmocc.zip -d "${HOME}/cosmopolitan"
    # shellcheck disable=SC2016
    echo 'export PATH="${PATH}:${HOME}/cosmopolitan/bin"' >> "${HOME}/.zshrc"
    export PATH="${PATH}:${HOME}/cosmopolitan/bin"
    install_ape_loader
    requires cosmocc
}
main "$@"
