#! /bin/bash
set -e

requires \
    opam \
    rsync \
    rustup
main() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local SRC_DIRECTORY="/refinedrust"
    export OPAMYES=1
    export OPAMFLAGS="$OPAMFLAGS -y"
    opam update
    opam upgrade
    eval $(opam env)
    git clone https://gitlab.mpi-sws.org/lgaeher/refinedrust-dev.git "${SRC_DIRECTORY}"
    cd "${SRC_DIRECTORY}" || exit
    opam switch create refinedrust --packages=ocaml-variants.4.14.0+options,ocaml-option-flambda
    opam switch link refinedrust .
    opam switch refinedrust
    opam repo add --best-effort rocq-released https://rocq-prover.org/opam/released
    opam repo add --best-effort iris-dev https://gitlab.mpi-sws.org/iris/opam.git
    opam pin add rocq-prover 9.1.0
    make builddep setup-dune typesystem
    cd "${SRC_DIRECTORY}/rr_frontend" || exit
    ./refinedrust build
    ./refinedrust install
    cd "${PWD}" || exit
    rm -frd "${SRC_DIRECTORY}"
}
main "$@"
