#! /bin/bash
set -e

requires \
    cargo \
    git \
    wget
main() {
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local VERUS_INSTALLATION_DIRECTORY="/verus"
    local VERUS_SOURCE="${VERUS_INSTALLATION_DIRECTORY}/source"
    git clone https://github.com/verus-lang/verus "${VERUS_INSTALLATION_DIRECTORY}"
    #
    # Install local z3
    #
    cd "${VERUS_SOURCE}/tools"
    bash ./get-z3.sh
    export VERUS_Z3_PATH="${VERUS_SOURCE}/tools/z3"
    #
    # Install Verus
    #
    cd "${VERUS_SOURCE}" || exit
    chmod +x "${VERUS_INSTALLATION_DIRECTORY}/tools/activate"
    "${VERUS_INSTALLATION_DIRECTORY}/tools/activate"
    "${VERUS_INSTALLATION_DIRECTORY}/tools/vargo/target/release/vargo" build --release
    ln -s "${VERUS_SOURCE}/target-verus/release/verus" /usr/local/bin/verus
    #
    # Install verusfmt
    #
    cargo install verusfmt --locked
    cd "${PWD}" || exit
}
main "$@"
