#! /bin/bash
set -e

requires \
    cargo \
    cleanup \
    git \
    why3 \
    z3
main() {
    #
    # Install system dependencies
    #
    apt-get update
    apt-get install --no-install-recommends -y \
        libcairo2-dev \
        libgtk-3-dev \
        libgtksourceview-3.0-dev
    cleanup
    #
    # Install Creusot
    #
    # shellcheck disable=SC2155
    local PWD="$(pwd)"
    local SRC_DIRECTORY="/creusot"
    git clone https://github.com/creusot-rs/creusot "${SRC_DIRECTORY}"
    cd "${SRC_DIRECTORY}" || exit
    ./INSTALL
    cargo creusot --help
    cd "${PWD}" || exit
}
main "$@"
