#! /bin/bash
# shellcheck disable=SC2155
set -e

requires \
    git \
    gum \
    stow
update_gold() {
    local COLOR="${GOLD_FOREGROUND_COLOR:-220}"
    local DOTFILES="${GOLD_DOTFILES:-"${HOME}/.dotfiles"}"
    local TITLE="Update $(gum style --foreground "${COLOR}" 'Complete')"
    git -C "${DOTFILES}" checkout -- .
    git -C "${DOTFILES}" pull origin main
    stow --dir "${DOTFILES}" --target /usr/local/bin --restow gold
    gum style \
        --border normal \
        --border-foreground "${COLOR}" \
        --margin "1" \
        --padding "1 2" \
        "${TITLE}"
}
update_package() {
    local DOTFILES="${GOLD_DOTFILES:-"${HOME}/.dotfiles"}"
    stow --dir "${DOTFILES}" --target "${HOME}" --restow "${1}"
}
main() {
    local DOTFILES="${GOLD_DOTFILES:-"${HOME}/.dotfiles"}"
    case "${1}" in
        update)
            update_gold
            ;;
        gold)
            update_gold
            ;;
        opencode)
            update_package "opencode"
            ;;
        *)
            echo "Usage: $(basename "${0}") [update|gold|opencode]"
            exit 1
            ;;
    esac
}
main "$@"
