#! /bin/bash
set -e

main() {
    if [[ "$(id -u)" -eq 0 ]]; then
        return
    fi

    if command -v sudo > /dev/null 2>&1; then
        exec sudo --preserve-env=ROOTLESS_USER,ROOTLESS_ONLY bash "$0" "$@"
    fi

    printf 'This script must run as root (or with sudo available).\n' >&2
    kill -SIGINT $$
}
main "$@"
