#! /bin/bash
set -e

requires \
    docker
main() {
    local COUNT="${1:-65536}"
    ulimit -n "${COUNT}"
    if [[ "$(id -u)" -eq 0 ]]; then
        service docker start
    else
        systemctl --user start docker.service
    fi
}
main "$@"
